### ISSUE TITLE
Glimmer components

### ISSUE THREAD

**Issue by knownasilya** [sandydoo/ember-google-maps#100]
I'd love to see this updated to use glimmer components to speed things up, especially when rendering many markers.

**Comment by sandydoo** [comment]
It’s coming 😉

**Comment by sandydoo** [comment]
This took much, _much_ too long, but, as of `4.0.0-beta.4`, the addon’s been completely converted to Octane. I haven’t done any comparison tests, but everything feels very snappy. [Panning around in the rentals example](https://ember-google-maps.sandydoo.me/examples/sweet-rentals/) (with the markers and listings constantly being replaced) is surpisingly fluid.

There are few things left to do, like figuring out backwards compatibility and breaking changes, but otherwise, I’d appreciate people testing it out in their apps. 🙌

**Comment by knownasilya** [comment]
Will give it a go tomorrow

**Comment by knownasilya** [comment]
Got this on build, looks like i might need to update something?

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-google-maps]) in ember-google-maps/effects/tracking.js

/Users/iradchenko/workspace/routinize/client/ember-google-maps/effects/tracking.js: @ember/runloop does not have a _backburner export
  1 | import { createCache, getValue } from '@glimmer/tracking/primitives/cache';
> 2 | import { _backburner } from '@ember/runloop';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  3 | import { registerDestructor } from '@ember/destroyable';
  4 |
  5 | /**
```

**Comment by knownasilya** [comment]
Maybe you need to use Ember global to access backburner?

**Comment by sandydoo** [comment]
Oh, thanks! I’ll look into it. Weird that the tests pass…

**Comment by sandydoo** [comment]
> Got this on build, looks like i might need to update something?

@knownasilya, turns out it’s because you have a slightly older version of `babel-plugin-ember-modules-api-polyfill`. I’ve set the minimum version we need as a dependency in `4.0.0-beta.6`. 😅

**Comment by knownasilya** [comment]
Hum, the new version still has the same issue.

**Comment by sandydoo** [comment]
I imagine upgrading your app’s dependencies should do the trick. `yarn upgrade` or `npm update`. If some older dependency is holding back the upgrade, then a `yarn why babel-plugin-ember-modules-api-polyfill` /`npm explain babel-plugin-ember-modules-api-polyfill` should show what’s going on.

Not sure what else I can do on my end. I can’t use the Ember global because it’s deprecated in `3.27`, and `babel-plugin-ember-modules-api-polyfill` is what maps modules to the Ember global in all Ember versions below `3.27`.

**Comment by knownasilya** [comment]
Will try that

**Comment by knownasilya** [comment]
So unfortunately almost every addon has this via `ember-cli-babel`, and each has a different version.

**Comment by sandydoo** [comment]
Yeah, that’s understandable. I think the one that matters is the version used by _your_ version of `ember-cli-babel`. So a `yarn upgrade` / `npm update` didn’t work, right?

**Comment by knownasilya** [comment]
Working now. Might need to specify in the docs the minimum version of ember-cli-babel and the need to do an upgrade/update as part of migration.

**Comment by sandydoo** [comment]
Landed in https://github.com/sandydoo/ember-google-maps/releases/tag/v4.0.0.
