### ISSUE TITLE
Infowindow issues

### ISSUE THREAD

**Issue by erzzo** [sandydoo/ember-google-maps#11]
Hey,
I'm using the infowindow attached to around 600 markers and the rendering is horribly slow, when I trie to hide and show one IW.
To boost the rendering, I've created only one IW with the lat, lng of an active item. But now the IW is not properly positioned, like in the example:
![image](https://user-images.githubusercontent.com/886192/39084360-eb940504-4574-11e8-984a-c8c48039f9bc.png)
It should float above the marker. How can I adjust the position of it? I found that there is a property pixelOffset for that.

**Comment by sandydoo** [comment]
Would mind sharing some more information:
* your initial code and format of your data
* the version of the Google Maps API you are using? v3.32 or v3.31?

#### Performance

I can't seem replicate your performance issue using 600 markers, so I can't suggest anything without more information.

```hbs
{{!-- An array of 600 lat/lng objects --}}
{{#each londonLocations as |l|}}
  {{!-- Toggle a property on the lat/lng object to open the info window --}}
  {{#g.marker lat=l.lat lng=l.lng onClick=(action (toggle "open" l)) as |m|}}
    {{#m.infoWindow isOpen=l.open}}
      {{l.lat}}, {{l.lng}}
    {{/m.infoWindow}}
  {{/g.marker}}
{{/each}}
```

#### Using a single `infoWindow`

You could use one `infoWindow` in this case. I haven't investigated the memory/cpu impact of having 600 infoWindows, so maybe it is a good idea. 

`pixelOffset` should work –  it's a matter of reading the [infoWindow API docs](https://developers.google.com/maps/documentation/javascript/reference/3/#InfoWindowOptions) and understanding the format it expects.

```hbs
{{g.infoWindow isOpen=openInfoWindow pixelOffset=(hash width=0 height=-20) content="Test"}}
```

However, instead of manually messing around with offsets, you can set the `target` and reattach the `infoWindow` between markers. This is mentioned in the [docs for this addon](https://ember-google-maps.sandydoo.me/docs/info-windows).

```hbs
{{g.infoWindow target=currentMarker isOpen=tooltipOpen content="Attached text tooltip"}}

{{#each londonLocations as |l|}}
  {{g.marker lat=l.lat lng=l.lng onClick=(action "setMarker")}}
{{/each}}
```

```js
actions: {
  setMarker({ target }) {
    this.set('currentMarker', target);
  }
}
```

**Comment by erzzo** [comment]
Thank you for your quick response. It's working now with your help.

And to the performance, the initial code has looked like this:

```handlebars
{{#g-map
  lat=defaultLat
  lng=defaultLng
  onLoad=(action "onMapLoaded")
  zoomControlOptions=(hash position=google.maps.ControlPosition.TOP_LEFT)
  streetViewControlOptions=(hash position=google.maps.ControlPosition.TOP_LEFT)
  zoom=15 as |g|
}}
  {{#each items as |item|}}
    {{#g.marker
      lat=item.lat
      lng=item.lng
      onClick=(action "openTooltip" item.id) // store to activeId
      as |m|
    }}
      {{#m.infoWindow isOpen=(eq item.id activeId)}}
        <div class="info-window">
          test
        </div>
      {{/m.infoWindow}}
    {{/g.marker}}
  {{/each}}
{{/g-map}}
```
Now when I click on the marker, my app freezes and it is taking some time the infowindow will be rendered. With only few markers it worked well.

I didn't used the version prop in the config, it probably loaded the newest version. But I've tried both versions with the same result.

**Comment by sandydoo** [comment]
Thanks for sending the code. I've had some time to look at this a bit closer and I think I know what's going on.

This addon creates an `options` object from the arguments you pass to `infoWindow`. These options are used to create and update `google.maps.InfoWindow`. Every time an argument (like `isOpen`) changes, the `options` are rebuilt and set using `setOptions`. 

There are 2 problems causing your grief:

#### The truth helper

Every time you modify `activeId`, Ember has to recalculate the value of `eq item.id activeId`. In your case, it ends up having to do this 600 times. This can be expensive in certain cases, e.g. when using `didUpdateAttrs`, like this addon does. In my tests, it takes about 150ms, so 2.5ms per `infoWindow`.

#### Performance of google.maps.InfoWindow

`content` is part of `options`. Google Maps will perform several *very* expensive DOM calculations every time it is set, even if the `content` hasn't actually changed. Worse, it will do so even if the `infoWindow` is closed. 

Reflow the DOM 600 times in a row and it's no wonder you're having issues. This results in at least 10 seconds of rendering on my laptop 🤣.

#### Reasonable workarounds

1. Avoid using the `eq` helper in the loop. Set the value on the object being displayed, if possible. That will cause 1 update instead of 600.

2. Use a single `infoWindow` and change the `target` on click, as suggested in my previous comment.

I'll have a look at how we can work around this issue. Maybe it'll be an observer, maybe I'll just set the `content` when the `infoWindow` is open.

**Comment by sandydoo** [comment]
@erzzo, 387c71ef39b8a71ddc96116cc926ded7b5c02219 should make your example more viable. I'll push out a release a bit later. Let me know if you get the chance to test out the master branch.

**Comment by erzzo** [comment]
@sandydoo how do you want me to test it? I only tried to set an isActive flag on the object itself and it worked perfectly fast!

**Comment by sandydoo** [comment]
Don't worry about it 👍 Glad it works 😁

**Comment by LucySuddenly** [comment]
I'm having another infoWindow issue: the isOpen option doesn't seem to be working. 

`  {{#g-map lat="39.0986106" lng="-98.6166598" zoom=4 as |g|}}
    {{#each this.model as |provider|}}
      {{#g.marker lat=provider.latlon.[0] lng=provider.latlon.[1] onClick=(action "toggle") as |m|}}
        {{#m.infoWindow isOpen=provider.markerOpen }}
          {{provider.name}}
        {{/m.infoWindow}}
      {{/g.marker}}
    {{/each}}
  {{/g-map}}`

I've verified that the toggle action is properly setting true false, but I can't get the infoWindow to respond

**Comment by sandydoo** [comment]
Hi @LucySuddenly, would you mind opening a new issue?

**Comment by LucySuddenly** [comment]
No problem, thank you!
