### ISSUE TITLE
Breaking change regarding @lng @lat

### ISSUE THREAD

**Issue by eelke** [sandydoo/ember-google-maps#120]
After upgrading from 3.0.3 to 4.0.1 none of my maps worked, throwing hard-to-debug issues:

``` Uncaught (in promise) TypeError: proxy set handler returned false for property '"center"'```, referring g-map.js line 81. 

Turns out that while previously the `@lng` and `@lat` were _not_ required in order to render a map,  as of 4.0.0 they _are_ required. 

I think the documentation should reflect this as a breaking change. 

I have the following use case where I don't set the map's position through the `@lng` and `@lat` arguments:

1. I add map to a template, and in its component/controller I have a list of markers
2. I then create a new `LatLngBounds`  object (`let bounds = new window.google.maps.LatLngBounds();`
3. I loop through the list of markers, add all of them to the `bounds` object (`bounds.extend(markerGeo);`)
4. I fit the map to the bounds object (`this.map.fitBounds(bounds);`) ..
5. ..and pan to the center of the bounds object (`this.map.panTo(bounds.getCenter());`)

**Comment by sandydoo** [comment]
Hi, @eelke 

> Turns out that while previously the `@lng` and `@lat` were not required in order to render a map, as of 4.0.0 they are required.

`@lat` and `@lng` are an optional alternative to `center`, but that doesn't mean that the addon ever officially supported using the map without any coordinates. [The docs are reasonably clear about this ](https://ember-google-maps.sandydoo.me/docs/map): `The only required arguments are the coordinates for the center.`

I guess `center` could be optional, since Google Maps doesn't care. I'm not going to advertise it as a feature though 🙈

**Comment by sandydoo** [comment]
@eelke, [I've released v4.1.0](https://github.com/sandydoo/ember-google-maps/releases/tag/v4.1.0) with a fix for your issue

**Comment by eelke** [comment]
Fantastic @sandydoo! Thank you for your continued work, it is much appreciated!
