### ISSUE TITLE
Get lat and long for address

### ISSUE THREAD

**Issue by jrock2004** [sandydoo/ember-google-maps#22]
### Complete this checklist before opening an issue

*Please read the documentation before opening an issue*. Once you understand how this addon works, you will find that most problems can be solved by consulting the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've read the relevant documentation for this addon on [ember-google-maps.sandydoo.me](https://ember-google-maps.sandydoo.me/docs/getting-started).

* [x] I understand how to set options on the components in this addon. Options are not hardcoded. Arguments passed to a component are used to set the options on the map component.

* [x] I've searched the relevant section of the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've [searched the closed issues](https://github.com/sandydoo/ember-google-maps/issues?q=is%3Aissue+is%3Aclosed) for similar problems.

--------------------------------------------------------------------------------

### Describe the bug
I do not have lat or long, does this addon get that data or would I need another addon to get it?

**Comment by sandydoo** [comment]
Hey, @jrock2004, providing a bit more context with your question always helps. I can't what you're doing, what you actually want to do or what you're expecting this addon to do for you.

I'm going to assume you have an address you want to geocode and display on a map.

I think the answer to your question is no. I also don't think you need extra addons either. This addon has a `googleMapsApi` service. You can use it to safely access Google's SDK, since it's loaded asynchronously. This actually takes care of the biggest problem of working with the Google SDK.

[Google has a comprehensive guide on geocoding.](https://developers.google.com/maps/documentation/javascript/geocoding)

Here's some sample code to get you started.

```js
import Service, { inject as service } from '@ember/service';
import { reads } from '@ember/object/computed';

export default Service.extend({

  googleMapsApi: service(),
  google: reads('googleMapsApi.google'),
  
  init() {
    this._super(...arguments);
    this.get('google').then((google) => {
       let geocoder = new google.maps.Geocoder();
       // Do your thing
  }
});
```

You can use a fancy promise-aware computed property if you'd like, which is what I use for the `DirectionsService` in this addon.

```js  
import { computedPromise } from 'ember-google-maps/utils/helpers';
```
```js
geocoder: computedPromise(function() {
  return this.get('google').then((google) => new google.maps.Geocoder());
})
```

You'd use it like this.
```js
this.get('geocoder').then((geocoder) => // ...);
```

**Comment by jrock2004** [comment]
@sandydoo So I am trying your example and google is null

```
import Component from '@ember/component';
import { inject as service } from '@ember/service';
import { reads } from '@ember/object/computed';

export default Component.extend({
  googleMapsApi: service(),
  tagName: '',
  isLoading: true,
  google: reads('googleMapsApi.google'),

  init() {
    this._super(...arguments);

    this.get('google').then((google) => {
      let geocoder = new google.maps.Geocoder();
    }).catch(() => {
      this.set('isLoading', false);
    }).finally(() => {
      this.set('isLoading', false);
    });
  }
});
```

**Comment by sandydoo** [comment]
I haven't seen any issues with the service in either apps and addons, so I would suggest making sure everything is installed with `ember install ember-google-maps`.

**Comment by lvl99** [comment]
I'm attempting the same, however there's no `computedPromise` util helper in the `ember-google-maps` addon.
