### ISSUE TITLE
Support runtime Google Maps URL configuration

### ISSUE THREAD

**Issue by GCheung55** [sandydoo/ember-google-maps#3]
The Google Maps URL is created at build time. It would be useful to be able to set some of the options, such as language or region, at runtime. E.g. determine the language or region from a user profile.

**Comment by sandydoo** [comment]
That seems reasonable. I think we can extract the bit that fetches the url from the config and allow you to override it by extending the `googleMapsApi` service.
The only concern I have is that Google Maps is loaded on-demand, as soon as the first `g-map` component is rendered. If generating the url is based on a user model, for example, then depending on how your app is structured, that model may or may not be available immediately. So the url function/prop would have to return a promise to be safe.

**Comment by ashotvardanyan** [comment]
Hi Guys !!
Is this planned to be implemented?

**Comment by mistahenry** [comment]
@sandydoo This is something I need in my app because I would like to provide the key only at runtime for users who are logged in (since google maps is so expensive now at least reduce the easiness of stealing my key). I'm happy to implement but I thought we could design it first. 

Is migrating away from `let src = ENV['ember-google-maps']['src'];` in your opinion a breaking change? I would like to enhance `service:google-maps-api` to provide the values from `env` as usual but have it do the url building instead

**Comment by sandydoo** [comment]
See #57 for a beta implementation.
The idea is that you can override the `buildGoogleMapsUrl` hook and return whatever URL you want.
If you decide to test it out, I'd appreciate feedback.

> at least reduce the easiness of stealing my key

While I totally understand your reasoning, I would like to discourage people from doing this.
These keys are essentially public and the two most effective ways of preventing abuse are:
1. Not *storing* the keys publicly, i.e. in a public Github repo.
2. Restricting your keys to specific domains.

**Comment by Windvis** [comment]
Is there anything blocking the merge of PR #57? Anything we can do to help? 😄
