### ISSUE TITLE
Uncaught TypeError: Cannot read property 'LatLng' of undefined

### ISSUE THREAD

**Issue by jasonjho** [sandydoo/ember-google-maps#33]
After following the readme and guide to get started, I am unable to render the most basic component. It seems as if the Google objects are not loaded at the point it's invoked. 

In looking at the Google Maps API docs, I see that ```https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap``` includes invoking a callback. Is this handled internally?

I've pretty much taken the exact steps in the Getting Started guide and can't seem to get past this.

Any tips?

**Comment by acorncom** [comment]
@jasonjho do you have any example code you can share? It's working fine for me in various client apps ...

**Comment by jasonjho** [comment]
Sure, here's what I have in my `config/environment.js`:

```
'ember-google-maps': {
      key: '<redacted>,
      language: 'en',
      region: 'US',
      protocol: 'https',
      version: '3.31',
      libraries: ['geometry', 'places']
    }
```
(note: I've tried specifying different API versions as well)

I have a basic `map.scss` file that I load with the rest of my stylesheets to give me the canvas:

```
.ember-google-map {
  width: 500px;
  height: 300px;
}
```

And finally, a very basic `hbs` component that contains: 

```{{g-map
  lat="42.3600825"
  lng="-71.05888010000001"
  zoom=18}}
```

When serving the page that renders this component, I get the following:

```
helpers.js:14 Uncaught TypeError: Cannot read property 'LatLng' of undefined
    at Class.<anonymous> (helpers.js:14)
    at ComputedPropertyPrototype.get (ember-metal.js:3390)
    at get (ember-metal.js:2761)
    at Object.getProperties (ember-metal.js:5582)
    at Class.<anonymous> (process-options.js:77)
    at ComputedPropertyPrototype.get (ember-metal.js:3390)
    at Object.get (ember-metal.js:2761)
    at Class.<anonymous> (g-map.js:115)
    at Generator.next (<anonymous>)
    at Class._resumeGenerator (-task-instance.js:535)
```

## Environment ##
Ember 3.0.0
I installed `yarn add ember-google-maps`

In my `package.json` I have:

```"ember-google-maps": "^2.0.4"```

**Comment by sandydoo** [comment]
Interesting! The clue here is that it's complaining about `maps` being undefined and not `google`.

https://github.com/sandydoo/ember-google-maps/blob/862a8ec1f0d20aba84a091700fc8a8abe90e6bed/addon/utils/helpers.js#L10

So the culprit is this short-circuit that checks whether we've already loaded the API. I assume `window.google` is not undefined in your case.
https://github.com/sandydoo/ember-google-maps/blob/862a8ec1f0d20aba84a091700fc8a8abe90e6bed/addon/services/google-maps-api.js#L44-L45

Definitely my bad for missing this. I'll release a patch now.
