### ISSUE TITLE
How to prevent Zoom in or Zoom Out on click

### ISSUE THREAD

**Issue by repl-soumya-c** [sandydoo/ember-google-maps#35]
Probably this is not a bug, more like a question. 
I have a map with default lat/lng set while rendering. Now I pan and zoom in and then click on the map. This triggers the click event and I get the new place lat/lng. However map zooms back to initial zoom position displaying the marker at the new place. 

I want to retain the zoom level whatever user have set before clicking. @sandydoo Could you please help me with that ?

**Comment by sandydoo** [comment]
It _sounds_ like you're modifying the initial `lat`/`lng` coordinates. If you want the current zoom level to persist, you have to set and update the `zoom` level as well, otherwise the default value will be used.

```hbs
{{g-map lat=lat lng=lng zoom=zoom}}
```

The map is zooming in and out because you're updating some of the options passed to the map without explicitly updating the `zoom` as well. There's no two-way binding between the map state and the options you pass in. So `lat` and `lng` are not automatically updated when you pan and neither is the `zoom` level when you zoom in or out. 

And @repl-soumya-c, as a general courtesy, please try to post the relevant code snippets in addition to describing the problem when opening issues. Thanks.

**Comment by repl-soumya-c** [comment]
Sorry about not adding the code snippet. Thanks for your prompt reply. Issue is resolved by setting zoom.
