### ISSUE TITLE
Is it possible to create cluster of custom overlays?

### ISSUE THREAD

**Issue by estshy** [sandydoo/ember-google-maps#37]
Documentation propose using custom overlays in place of markers whenever more advances formatting is required. Google provides a few nice solution that are handy to use with map that is based on many markers, ie. https://developers.google.com/maps/documentation/javascript/marker-clustering. Is there anything similar that can be used as replacement for overlays?

**Comment by sandydoo** [comment]
@estshy, I'm not convinced I implied that you should use overlays instead of clustering 😅 
We don't yet have a clustering component, but I think it's worth adding. Going to add this request towards the next release.
You can try following @acorncom suggestions, but there isn't any concrete documentation other than a sample addon implementation.

**Comment by lolmaus** [comment]
I have looked into clusterizing vanilla markers (not custom overlays), and turns out that adding this feature to the addon is quite challenging.

I doubt that it can be done with an ember-google-maps-addon without heavily modifying the core addon:

* the clusterer has to be initialized on the map level;
* the markers must have a reference to the clusterer;
* lots of options must be exposed to allow clusterer configuration;
* etc.

On the other hand, clusterizing in the userland is quite easy. The sample below is written from my head, might need adjustments to actually work:

```js
import MarkerClusterer from '@googlemaps/markerclustererplus';

{
@action
onLoad({map, components: {markers}}) {
    new MarkerClusterer(
      map,
      markers: markers.map(item => item.markers),
      {
        // Should correspond to app.import in ember-cli-build.js
        imagePath: 'assets/images/google-maps-clusterer/m',
      }
    );
}
}
```

```js
  // ember-cli-build.js
  const clustererImagesPath = 'node_modules/@googlemaps/markerclustererplus/images';

  fs.readdirSync(clustererImagesPath).forEach(file => {
    const fileFullPath = path.join(clustererImagesPath, file);
    app.import(fileFullPath, {
      destDir: 'assets/images/google-maps-clusterer'
    });
  });
```

I don't know if https://github.com/googlemaps/js-markerclustererplus can be retrofitted to clusterize custom overlays. Maybe Glimmer components can be duck-typed to mimic as markers... In the worst case, this lib can be ported into the Ember land, and it doesn't necessarily have to be hardwired into `ember-google-maps`.

**Comment by lolmaus** [comment]
PS Just noticed this thread is two and a half years old! 🙀

**Comment by sandydoo** [comment]
> I have looked into clusterizing vanilla markers (not custom overlays), and turns out that adding this feature to the addon is quite challenging.

https://github.com/sandydoo/ember-google-maps-markerclustererplus is almost ready. Should be plug-n-play with ember-google-maps 🤞

> Is there anything similar (clustering) that can be used as replacement for overlays

AFAIK there is no ready-made solution for this. I reckon the clustering library will likely accept an overlay view that mimics a marker. But don't quote me on that.

This feature is out of the scope of this addon, unless someone is generous enough to fund it.
