### ISSUE TITLE
Add some CSS to support printing?

### ISSUE THREAD

**Issue by acorncom** [sandydoo/ember-google-maps#50]
### Complete this checklist before opening an issue

*Please read the documentation before opening an issue*. Once you understand how this addon works, you will find that most problems can be solved by consulting the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've read the relevant documentation for this addon on [ember-google-maps.sandydoo.me](https://ember-google-maps.sandydoo.me/docs/getting-started).

* [x] I understand how to set options on the components in this addon. Options are not hardcoded. Arguments passed to a component are used to set the options on the map component.

* [x] I've searched the relevant section of the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've [searched the closed issues](https://github.com/sandydoo/ember-google-maps/issues?q=is%3Aissue+is%3Aclosed) for similar problems.

--------------------------------------------------------------------------------

### Describe the bug
I've been building a complex map over the last few months for a client and one of the latest feature requests was that we be able to print it in-browser, allowing folks to specify zoom and positioning for the map. When printed in Webkit-based browsers, we were seeing map tiles tear as outlined in this Chromium bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=426294

The official Google Maps line on printing is that [printing isn't supported](https://developers.google.com/maps/faq#print) and the common recommendation is that the Google Static Maps API be used instead. But in my particular use case, there is no way we'll fit inside the size constraints of the Google Static Maps API and there is enough state in the browser that we track that doing printing on the backend could be a royal pain. 

Per the bug report above, it looks to be an issue with Google Maps / Webkit browsers and there is also a CSS fixed suggested: https://bugs.chromium.org/p/chromium/issues/detail?id=426294#c13

That CSS tweak ended up fixing my issues (so far, 🤞). So my question is, would we want to consider adding that CSS to this addon to keep other folks from getting snagged in the future? I can see going either way (Google Maps **might** incorporate the fix themselves or some variant down the road, which would mean we'd be shipping unneeded CSS in this addon for a long time). But it caused enough headaches on this end that I thought I'd bring the idea up ...

Thoughts?

**Comment by sandydoo** [comment]
Yeah, I understand.

I am worried about modifying the styling of the tiles. While I don't expect that adding another `position: absolute;` should break anything, the fact that it fixes the printing issues worries me.

The workaround itself is surprisingly simple, so the actual pain is from the difficulty of finding the information.
On the other hand, I expect that most people expect printing to "just work" and are going to be stung by this. So unless the fix is enabled by default, they'll still run into the issue. 

Here's the dilemma. Do we: 
* ship a workaround to everyone that could have unintended consequences?
* or make the workaround/information accessible to those that need it?

I personally prefer the second option. Perhaps it's less practical or proactive, but at least it's accessible and documented.
At the end of the day, is it worth figuring out a css pipeline, tracking which map versions need the fix, bearing the responsibility of messing with the tiles, and so on? Probably not.

**Comment by acorncom** [comment]
Yep, that works for me. I wasn't sure the idea of taking the responsibility for messing with the tiles would be appealing 😉 Preferences on how/where we go about adding documentation for it? Seems like an additional page after "Complex UI" would be in order, happy to send in a PR if you want

**Comment by sandydoo** [comment]
> Preferences on how/where we go about adding documentation for it? Seems like an additional page after "Complex UI" would be in order, happy to send in a PR if you want

Sure 👍

**Comment by gilest** [comment]
Was facing a similar problem and found this issue.

Added the CSS workaround inside `@media print {}` in my project. Also included a comment linking the Chromium issue.

I think it's reasonable for users of the addon to maintain this in their own projects. We can hopefully remove it when Chromium is patched.

Thanks for investigating and sharing your findings :)

**Comment by sandydoo** [comment]
Closing this, as it's more of a Google Maps issues. I think this issue has enough "searchability" to be useful by itself 😄
