### ISSUE TITLE
Add component(s) for working with Google Maps Data layer

### ISSUE THREAD

**Issue by steveszc** [sandydoo/ember-google-maps#6]
The google maps Data layer is useful for rendering arbitrary geospatial data onto map in the form of GeoJSON and polygons. It'd be great if `ember-google-maps' provided a components for adding and styling GeoJSON data and polygons.

https://developers.google.com/maps/documentation/javascript/3.exp/reference#Data

**Comment by sandydoo** [comment]
I haven't had the pleasure of working with the `Data` classes, but I am familiar with GeoJSON. I've had a look at the spec over the weekend and have some ideas I wanted to share.

The `Data` class manages a collection of `Features` - points, lines, polygons, etc. These `Feature`s map one-to-one to GeoJSON types. So essentially, the `data` class lets you load/display GeoJSON or build your own GeoJSON (object?) out of individual building blocks.

Based on that summary, the problem boils down to three things: managing collections of features (`data`), displaying existing `GeoJSON` and creating `GeoJSON` using the individual `Feature` / `Geometry` classes. 

This spec is a bit different than the regular map components, so that needs to be taken into account. We may also have to add a few management features that diverge from the vanilla Google Maps API.

Basic idea:

1. A `data` component that manages the collection of `Feature`s added to the map. Multiple `data` components can be used. These `Data` collections will be accessible via the `publicAPI` hash yielded and returned with every event. We could allow passing a custom `id` or `name` to differentiate `data` collections.

2. The `data` component should yield some `geoJson` component to easily add GeoJSON data to the map. This should be the basic functionality. This basically wraps the `addGeoJson`/`loadGeoJson` methods. We could probably allow a `url` or a `data` attribute to handle both methods. We could even loop over the features parsed from the GeoJSON and populate our own arrays of `Geometry` types.

3. The `data` component could later yield tiny wrapper components that add `Feature`s to the parent collection. This is the more advanced/involved option for displaying data. I assume these allow more more granular control over the data by allowing users to add GeoJSON features separately. The big difference compared to regular map components, is that these are "added" to the map, whereas the regular components are assigned a map with `setMap`. These `Feature` components are wrappers around the `add` method. There are 8 `Geometry` classes that map one-to-one to GeoJSON types. They are all very similar, so could share almost all their logic via some base `feature` component. Each would accept an `id`, `properties` and some data to pass the the relevant `Geometry` class. 

The relevant `Geometry` classes (aka GeoJSON types):
`Point`, `MultiPoint`, `LineString`, `MultiLineString`, `LinearRing`, `Polygon`, `MultiPolygon`, or `GeometryCollection`.

```hbs
{{#g-map lat=lat lng=lng as |g|}}
  {{g.data style=(hash ...) as |d|}}
    {{d.geoJson ... }}
  {{/g.data}}
  {{!-- Another collection of data. Needs to have a name or id --}}
  {{g.data style=(hash ...) as |d|}}
     ...
  {{/g.data}}
{{/g-map}}
```

Open questions: 

* How do we work with `overrideStyle` and `revertStyle`? Managing this via the parent class seems strange to me. We could allow passing a `style` hash to the child `Feature` classes and handle the `overrideStyle` behind the scenes. This is not vanilla API, but it makes way more sense to me.

* How crazy do we go with the individual `Feature` components. Should `multiLineString` yield `lineStrings` and so on? How granular does this have to be?

**Comment by sandydoo** [comment]
I've started working on this behind the scenes using the new addon system (#17). Working out quite well! I'll try to make it public soon.

**Comment by acorncom** [comment]
@sandydoo one other thing to bear in mind as you work on the data addon. Once there is the ability to draw geojson on a map, the ability to edit said shapes quickly comes up. That was the heart of the question behind @knowasilya’s question about plugins in https://github.com/sandydoo/ember-google-maps/issues/1 Google adds the ability to use a drawing manager and edit feature/polygons, which I think would be the long-term hope of some of us who use the data system. So something worth considering as you experiment with the data plugin. Looking forward to seeing what you come up with! Let me/us know if you want early testers/feedback ...

**Comment by knownasilya** [comment]
@sandydoo how's that coming along? Any alpha/beta branches?

**Comment by acorncom** [comment]
@sandydoo I'm interested in alpha/beta branches here as well 😉
