### ISSUE TITLE
Directions Panel

### ISSUE THREAD

**Issue by jayvarner** [sandydoo/ember-google-maps#61]
Thanks for all the work on this addon. It's fantastic.

As you mention in the docs, getting the bits out of the directions object for a route can be a pain. I'm sure you're aware of the method [setPanel()](https://developers.google.com/maps/documentation/javascript/examples/directions-panel) on the `DirectionsRenderer` that will insert formatted turn by turn instructions into the element passed to the method. Would you have any interest in a PR to add an option to pass an element's id to the route component? I took a [first pass](https://github.com/jayvarner/ember-google-maps/blob/develop/addon/components/g-map/route.js). I'm happy to make changes to match style preferences, add tests, update the docs, and whatnot.

Again, thanks for all hard work here.

**Comment by sandydoo** [comment]
> Thanks for all the work on this addon. It's fantastic.

Thank you! I'm truly sorry this took so long. No excuses, I just kept delaying this to my backlog. 😞 

>  I'm sure you're aware of the method setPanel() on the DirectionsRenderer

Actually, I had no idea 😄.

> add an option to pass an element's id to the route component

I think the answer would be no. Don't get me wrong, what you're proposing is _totally fine,_ just not in the context of an addon. As an addon maintainer, I don't want to bear the responsibility of grabbing a remote element from the user space and messing with it. It seems like it would inevitably lead to conflict.

Do I just run `setPanel` when the directions load? Would you want to know when I do this so that you can style your element / UI? As soon as you need something slightly more than just "run `setPanel`", the addon now has to manage the entire lifecycle of the directions panel. But there's no reason to go through the addon at all. It can all remain under the end user's control.

So how would I approach this problem? It turns out there are several good options.

1. Using `onDirectionsChanged` on the `directions` component.

```hbs
{{#g.directions onDirectionsChanged=(action this.showDirectionsPanel) as |d|}}
```

2. A helper / component. This can take an element, an id, or create a new element itself. Perhaps it wormholes it somewhere else, but it's declared and controlled here.

```hbs
{{#g.directions ... as |d|}}
  {{directions-panel d.directions}}
{{/g.directions}}
```

3. A custom component. Yeah, I know I never wrote the docs on this, but another option is to extend the route component and modify it, similar to what you proposed. Place it in `components/g-map-addon/` and it will be yielded by `g-map`, like all the other components in this addon.

I hope someone finds this helpful.
